version: 2.1

jobs:
  runner-test:
    machine: true
    resource_class: laxmanjun01/changiapp3
    steps:
      - run: echo "Hi I'm on Runner 2"
      
workflows:
  testing:
    jobs:
      - runner-test
